%2023-10-12% %00:06:08.162808% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee17.py", line 74, in <module>
    r = Recruiter("Nata", 20, "Master of recruting", "nata@gmail.com")
  File "/home/vadim/alevel/a-level-vadim/OOP/employee17.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee17.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee17.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:08:00.880925% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 113, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 17, in __init__
    self.validate()
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 46, in validate
    raise EmailAlreadyExistsException(f"email {self.email} already exist in emails.csv")
EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:08:39.125627% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:09:29.190620% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:09:49.820844% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:17:44.643985% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:18:19.482599% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:22:30.911723% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:24:06.585997% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:30:05.717659% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:31:44.798605% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:31:52.526938% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:32:21.240846% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:35:08.492260% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%%2023-10-12% %00:35:33.967574% | %Traceback (most recent call last):
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 112, in <module>
    r = Recruiter(
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 16, in __init__
    self.save_email(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 34, in save_email
    self.validate(email)
  File "/home/vadim/alevel/a-level-vadim/OOP/employee18.py", line 45, in validate
    raise EmailAlreadyExistsException(f"email {email} already exist in emails.csv")
OOP.employee18.EmailAlreadyExistsException: email nata@gmail.com already exist in emails.csv
%